---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
options(width = 100)
```
# dataset

<!-- badges: start -->
<!-- badges: end -->

`dataset` 패키지는 LG 인화원의 교육을 위해서 작성한 데이터 패키지입니다.

## 설치

`dataset` 패키지는 아래 코드를 이용해 설치할 수 있습니다.
`remotes` 패키지는 설치되어 있지 않다면 설치해야 `github`내의 패키지를 설치할 수 있습니다.

``` r
install.packages("remotes")
remotes::install_github("lgleadershipacademy/dataset")
```

## 사용할 수 있는 데이터 리스트

```{r}
library(dataset)
library(dplyr)
list_of_dataset()
```

## 데이터 사용

리스트내에 `mining_sample`과 같이 데이터셋 이름의 뒤에 `_sample` 이 붙은 데이터가 아니라면 바로 이름으로 사용할 수 있습니다.

```{r}
avocado
glimpse(avocado)
```

## mining_sample

`mining` 데이터셋은 용량이 커서 다운로드로 제공하며, 패키지 내에는 `mining_sample`로 첫 100줄의 데이터만 확인할 수 있습니다.
전체 데이터를 불러오려면 `get_mining_data()` 함수를 사용하시면 됩니다.

```{r cache=T}
mining <- get_mining_data()
glimpse(mining)
```
